apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitness-backend
  template:
    metadata:
      labels:
        app: fitness-backend
    spec:
      containers:
      - name: fitness-backend
        image: pathuripadmini/fitness-backend:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/fitness_tracker?useSSL=false&serverTimezone=UTC
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: fitness-secrets
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fitness-secrets
              key: MYSQL_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: fitness-secrets
              key: JWT_SECRET
