apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitness-frontend
  template:
    metadata:
      labels:
        app: fitness-frontend
    spec:
      containers:
      - name: fitness-frontend
        image: pathuripadmini/fitness-frontend-dev:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_BASE_URL
          value: "http://fitness-backend:8081"
