apiVersion: v1
kind: Secret
metadata:
  name: fitness-secrets
type: Opaque
stringData:
  MYSQL_USER: root
  MYSQL_PASSWORD: Padmini@12
  MYSQL_DB: fitness_tracker
  JWT_SECRET: YourLongRandomJwtSecretString_ChangeThis
